stages:
  - build_qa
  - deploy_qa


build_es_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  stage: build_qa
  variables:
    AWS_ACCESS_KEY_ID: $QA_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $QA_AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg STAGE=qa  -f elasticsearch/Dockerfile.production -t "$QA_ECR_ES_BASE_URL:$CI_COMMIT_SHA"  .
    - docker push "$QA_ECR_ES_BASE_URL:$CI_COMMIT_SHA"
  only:
    - gitlab/test

build_kibana_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  stage: build_qa
  variables:
    AWS_ACCESS_KEY_ID: $QA_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $QA_AWS_SECRET_ACCESS_KEY
    ELASTICSEARCH_URL : $ELASTICSEARCH_URL
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build  -f kibana/Dockerfile.production -t "$QA_ECR_KIBANA_BASE_URL:$CI_COMMIT_SHA"  .
    - docker push "$QA_ECR_KIBANA_BASE_URL:$CI_COMMIT_SHA"
  only:
    - gitlab/test

build_api_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  stage: build_qa
  variables:
    AWS_ACCESS_KEY_ID: $QA_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $QA_AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - d=configurator/check/qa/alegre/; for f in $(find $d -type f); do cp "$f" "${f/$d/}"; done
    - docker build  -f docker/Dockerfile.production -t "$QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"  .
    - docker push "$QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"
  only:
    - gitlab/test




deploy_qa:
  image: python:3
  stage: deploy_qa
  variables:
    AWS_ACCESS_KEY_ID: $QA_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $QA_AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - pip install awscli
    - apt-get update
    - apt-get install -y jq
    - curl 'https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy' | tee /usr/bin/ecs-deploy
    - chmod +x /usr/bin/ecs-deploy
    - ecs-deploy -c ecs-qa  -n qa-alegre-es -i $QA_ECR_ES_BASE_URL:$CI_COMMIT_SHA -t 3600 --skip-deployments-check
    - echo "new Image was deployed $QA_ECR_ES_BASE_URL:$CI_COMMIT_SHA"
    - ecs-deploy -c ecs-qa  -n qa-alegre-kibana -i $QA_ECR_KIBANA_BASE_URL:$CI_COMMIT_SHA -e qa-alegre-kibana-c ELASTICSEARCH_URL $ELASTICSEARCH_URL  -t 3600 --skip-deployments-check
    - echo "new Image was deployed $QA_ECR_KIBANA_BASE_URL:$CI_COMMIT_SHA"
    - ecs-deploy -c ecs-qa  -n qa-alegre -i $QA_ECR_API_BASE_URL:$CI_COMMIT_SHA -e qa-alegre-c ELASTICSEARCH_URL $ELASTICSEARCH_URL -e qa-alegre-c PRODUCT $PRODUCT --t --skip-deployments-check
    - echo "new Image was deployed $QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"
  only:
    - gitlab/test