stages:
  - build_qa
  - deploy_qa
  - build_live
  - deploy_live

build_api_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build_qa
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build  -f docker/Dockerfile.production -t "$QA_ECR_API_BASE_URL:$CI_COMMIT_SHA" .
    - docker push "$QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"
  only:
    - develop

deploy_qa:
  image: python:3-alpine
  stage: deploy_qa
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - apk add --no-cache curl python py-pip git
    - pip install ecs-deploy==1.7.0
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - source configurator/check/qa/alegre/.env_file
    - ecs deploy ecs-qa  qa-alegre --image qa-alegre-c $QA_ECR_API_BASE_URL:$CI_COMMIT_SHA -e qa-alegre-c ELASTICSEARCH_URL $ELASTICSEARCH_URL -e qa-alegre-c PROVIDER_LANGID $PROVIDER_LANGID -e qa-alegre-c BOILERPLATE_ENV $BOILERPLATE_ENV -e qa-alegre-c REDIS_HOST $REDIS_HOST -e qa-alegre-c REDIS_PORT $REDIS_PORT -e qa-alegre-c REDIS_DATABASE $REDIS_DATABASE -e qa-alegre-c MS_TEXT_ANALYTICS_KEY $MS_TEXT_ANALYTICS_KEY -e qa-alegre-c MS_TEXT_ANALYTICS_URL $MS_TEXT_ANALYTICS_URL --timeout 3600
    - echo "new Image was deployed $QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"
  only:
    - develop

deploy_live:
  image: python:3-alpine
  stage: deploy_live
  when: manual
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install ecs-deploy==1.7.0
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - source configurator/check/live/alegre/.env_file
    - ecs deploy ecs-live  live-alegre --image live-alegre-c $LIVE_ECR_API_BASE_URL:$CI_COMMIT_SHA -e live-alegre-c ELASTICSEARCH_URL $ELASTICSEARCH_URL -e live-alegre-c PROVIDER_LANGID $PROVIDER_LANGID -e live-alegre-c BOILERPLATE_ENV $BOILERPLATE_ENV  -e live-alegre-c REDIS_HOST $REDIS_HOST -e live-alegre-c REDIS_PORT $REDIS_PORT -e live-alegre-c REDIS_DATABASE $REDIS_DATABASE -e live-alegre-c MS_TEXT_ANALYTICS_KEY $MS_TEXT_ANALYTICS_KEY -e live-alegre-c MS_TEXT_ANALYTICS_URL $MS_TEXT_ANALYTICS_URL --timeout 3600
    - echo "new Image was deployed $LIVE_ECR_API_BASE_URL:$CI_COMMIT_SHA"
  only:
    - master
