version: '2'
volumes:
  esdata:
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL: http://elasticsearch:9200"
  alegre:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - kibana
    volumes:
      - ".:/app"
    environment:
      - "BOILERPLATE_ENV: dev"
