version: '2'
volumes:
  elasticsearch:
  redis:
  postgres:
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      transport.host: 127.0.0.1
      xpack.security.enabled: "false"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.5
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alegre
  model_use_multilingual_large:
    build: .
    command: ["make", "run_model"]
    volumes:
      - ".:/app"
    depends_on:
      - redis
    env_file:
      - .env_file
    environment:
      MODEL_CLASS: UniversalSentenceEncoder
      MODEL_KEY: universal-sentence-encoder-multilingual-large
      MODEL_OPTIONS: '{"model_path": "https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3"}'
  model_laser:
    build: .
    command: ["make", "run_model"]
    volumes:
      - ".:/app"
    depends_on:
      - redis
    env_file:
      - .env_file
    environment:
      MODEL_CLASS: LaserSharedModel
      MODEL_KEY: laser
      MODEL_OPTIONS: '{}'
  model_sbert:
    build: .
    command: ["make", "run_model"]
    volumes:
      - ".:/app"
    depends_on:
      - redis
    env_file:
      - .env_file
    environment:
      MODEL_CLASS: Sbert
      MODEL_KEY: sbert
      MODEL_OPTIONS: '{}'
  alegre:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
      - kibana
      - redis
      - model_use_multilingual_large
      - model_laser
      - model_sbert
    env_file:
      - .env_file
