version: '2'
volumes:
  elasticsearch:
  redis:
networks:
  dev:
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ALEGRE_URL=http://alegre:5000"
    networks:
      - dev
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - "5601:5601"
    networks:
      - dev
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    networks:
      - dev
  alegre:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - kibana
      - redis
    networks:
      - dev
    env_file:
      - .env_file
    environment:
      - "BOILERPLATE_ENV=dev"
