version: '2'
volumes:
  esdata:
networks:
  dev:
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ALEGRE_URL=http://alegre:5000"
    networks:
      - dev
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - "5601:5601"
    networks:
      - dev
    environment:
      - "ELASTICSEARCH_URL: http://elasticsearch:9200"
  alegre:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    networks:
      - dev
    environment:
      - "BOILERPLATE_ENV: dev"
